version: '2.1'
services:
 
  roundcube-mailcow:
    image: hub.cybergate.lk/openemail/roundcube:gmail_plus
    environment:
      - TZ=${TZ}
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://dovecot
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=postfix
      - ROUNDCUBEMAIL_SMTP_PORT=588
      - ROUNDCUBEMAIL_PLUGINS=archive,managesieve,zipdownload,password,xframework,xskin,carddav
      - ROUNDCUBEMAIL_SKIN=gmail_plus
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=25M
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=mysql
      - ROUNDCUBEMAIL_DB_PORT=3306
      - ROUNDCUBEMAIL_DB_USER=${DBUSER}
      - ROUNDCUBEMAIL_DB_PASSWORD=${DBPASS}
      - ROUNDCUBEMAIL_DB_NAME=roundcube
    volumes:
      - ./data/roundcube/:/var/www/html/

    depends_on:
      - mysql-mailcow
    restart: always
    networks:
      mailcow-network:
        aliases:
          - roundcube
