version: '2.1'
services:
 
  roundcube-mailcow:
    image: hub.cybergate.lk/openemail/roundcube:OPENEMAIL_VERSION
    container_name: roundcube
    hostname: ${MAILCOW_HOSTNAME}
    environment:
      - TZ=${TZ}
      - ROUNDCUBEMAIL_DEFAULT_HOST=${MAILCOW_HOSTNAME}
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=postfix
      - ROUNDCUBEMAIL_SMTP_PORT=588
      - ROUNDCUBEMAIL_PLUGINS=archive,zipdownload,password,xframework,xskin,carddav
      - ROUNDCUBEMAIL_SKIN=gmail_plus
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=25M
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=mysql
      - ROUNDCUBEMAIL_DB_PORT=3306
      - ROUNDCUBEMAIL_DB_USER=${DBUSER}
      - ROUNDCUBEMAIL_DB_PASSWORD=${DBPASS}
      - ROUNDCUBEMAIL_DB_NAME=roundcube
    volumes:
      - ./data/roundcube/:/var/www/html/

    depends_on:
      - mysql-mailcow
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      mailcow-network:
        aliases:
          - roundcube
